# Generated by Django 3.2.25 on 2024-12-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sucursal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
