# Generated by Django 3.2.25 on 2024-12-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_sucursal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sucursal',
            new_name='branch',
        ),
    ]
