# Generated by Django 3.2.25 on 2024-12-04 05:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.pest_image_file_path),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
