# Generated by Django 3.2.25 on 2024-12-08 02:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20241204_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='avata.png', null=True, upload_to=core.models.user_image_file_path),
        ),
    ]
