# Generated by Django 3.2.25 on 2024-12-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_technique',
            field=models.BooleanField(default=False),
        ),
    ]
