# Generated by Django 3.2.25 on 2024-12-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_workrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='status',
            field=models.CharField(choices=[('send', 'Send'), ('submitted', 'Submitted'), ('working', 'Working')], default='submitted', max_length=10),
        ),
    ]
